### ISSUE TITLE
Error is getting

### ISSUE THREAD

**Issue by maamirh** [ch2sh/Jlaive#1]
When I am clicking on build I am getting this error.
![image](https://user-images.githubusercontent.com/46965638/168274168-cf24d1b5-3252-401b-a99e-b17744cd01ec.png)

**Comment by ch2sh** [comment]
Please ensure that you extracted both Jlaive and JlaiveCLI to the same directory.

**Comment by maamirh** [comment]
Yes resolved.Thanks.
