### ISSUE TITLE
you can add startup

### ISSUE THREAD

**Issue by tarekxxx** [ch2sh/Jlaive#3]
all i need in this startup in Task Scheduler it will be awesome 
because its lose when i restart and even delete my start up in my program

**Comment by ch2sh** [comment]
Jlaive doesn't stop your program from adding to startup. You are required to implement startup persistence yourself in your own program. Jlaive performing startup persistence for you will not be as effective.

**Comment by tarekxxx** [comment]
so cant make like startup or Task Scheduler because i cant make my program working with your bat and i try alot bot not effective it will be awesome help me aloot

**Comment by ch2sh** [comment]
Fine, I will add startup. But the code actually does know where the batch file is located. The .exe extension is just appended at the end. You just need to remove the extension to get the location of the batch file.

**Comment by tarekxxx** [comment]
i disabled my startup then enabled your startup and run batch then restart nothing happen
